### ISSUE TITLE
Call for contributions required for CITS 3DPM

### ISSUE THREAD

**Issue by stephenmackey** [DILCISBoard/CITS-3DPM#2]
CITS 3DPM is now ready for review and located in the repository CITS-3DPM branch rel/v1.0.0. A call for contributions is required with review period and planned publication dates.

**The suggestion is:**

Publication of the CfC on the 15th  of July which will be open until the 15th of October. Publication end of October.

**Board members acknowledgment of the issue:**

Tick the box in front of you name to indicate that you have looked at the suggestion.
 
- [x] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [x] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [x] Gregor Zavrsnik (Geoarh)
- [x] Janet Anderson (Highbury Research & Development Ltd.)
- [x] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [x] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**

(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.

- [x] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [x] Gregor Zavrsnik (Geoarh)
- [x] Janet Anderson (Highbury Research & Development Ltd.)
- [x] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [x] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by karinbredenberg** [comment]
6 DILCIS Board members have acknowledge the issue
5 DILCIS Board members agree with the solution

The call for comments will be released

**Comment by stephenmackey** [comment]
Review closed with 2 responses, issues to be raised agaimst comments.
